### ISSUE TITLE
Design asset distribution case

### ISSUE THREAD

**Issue by kabergstrom** [amethyst/atelier-assets#18]
While the asset daemon and RPC Loader works well for development environments, we should design distribution scenarios to support our current and upcoming target platforms.

- Windows/OSX/Linux
- Mobile (packaged with app, separately downloaded)
- Consoles (Switch, XBox, PS4)
- Web (WASM)

WASM and PC are probably highest priority.

**Comment by valkum** [comment]
Here are some thoughts from me:
### Distribution
There are different ways to distribute your game.
Platforms like Steam, Epic, Gog which have a client. 
Websites which offer a simple download: Your website, itch.io?, Humble Bundle (when DRM-free)
Platforms can offer some support with some points on my list like patching but as we want to support Website downloads and WASM well we should think about those issues as well.

### Container
We should have some kind of asset container/asset bundle files
Something like Valves VPK. Do we have people on board who are experienced using the formats used by other engines?
What would be the use case for a single container?
What would be the use case for multiple containers? One per state? Different asset resolutions?
What file size should a container have?
Topics are fragmentation, seeking, syscalls, etc.

### Patching
Patching of asset "containers/files" should be possible (but maybe optional)
Nobody likes to download the complete game after an update to the assets.
ishitatsuyuki said in discord that patching is done by steam for example. But we should also support the use case of providing the installer/updater/patcher by yourself. For example when you provide DRM free versions on your homepage.

Also for WASM, there should be a way to patch a cached file rather than download the full new version of that file depending on size. Not sure if this would be possible. If we download single asset files (see further down) rather than containers, download of the new file version should be fine I guess.
If we store a container in the browser cache or wherever downloading the whole container because of an update would be a bummer.

### Integrity Protection
Some kind of integrity protection would be nice.
This should prevent parties from changing game content e.g. prefabs.
A basic version could use checksums, but this could get quite resource intensive. I don't want to calculate the checksum for my cinematic intro video. 
Maybe different methods for kinds of assets? Checksums for prefabs should be fine.
As Anti Cheat measurements are basically different layers, this is one of the basic ones to prevent the easiest kind of cheating.
Should be configurable to allow some kind of modding.

### Compression
Compression would just increase load times. Most games with huge assets file most likely will use asset files that are compressed already (DXTn)
Users can use their OS compression if they want to save space.

### Prevent asset extraction
Some devs seem to care about asset extraction. 
One way to prevent that would be to encrypt the asset container on disk. But then we need to decrypt our assets during load, possibly increasing load times. 
Just encrypting our container would maybe result in the need to decrypt the whole container before actual loading can begin. This has to be avoided.
Loading of a single file from this container should be possible.

We cannot count on obfuscation of our distributed file format, because eventually this would be well documented somewhere in the amethyst/atelier book.

We could have an index file which is encrypted using a strong encryption method and the actual assets are garbled. Essentially making the index file kind of a key for the asset container.
A solution for this should include performance consideration.

Sure, there are always ways to extract assets (dumping them from your GPU e.g.) but remember: _layered security_.

### Asset Streaming
No not streaming to your GPU but rather allowing the WASM game to load the assets from your server on load. So you only have to load files that you are loading right now. Reducing first loading times.
After the first load, the file should be cached. 
Do we want to assemble a container in the browser our just store the single asset files in the cache?

### Installer (Windows)
Do we want our own installer for windows?
Or should we use (and provide information on how to use) something like NSIS with amethyst?
Ref.: Patching and Platformless distribution.

### Support for early play
Blizzards Battle.net client allows you to play the game before you finish downloading all assets.
This is something our container should support as well. Maybe splitting high detail assets into a single container and the medium and low into another. Then someone can play with medium settings after downloading the first container and the high resolution asset container would be downloaded in the background.

Amethyst should be able to be notified that the download is finished and use the high res assets when notified if the user selected the high res assets in settings previously.
(This, most likely, is not an issue for 2D games)

**Comment by kabergstrom** [comment]
Thanks for your thoughts @valkum! Really good stuff. Hope we can push forward with more details around platform limitations, recommended practices and use-cases.

> ### Distribution
> There are different ways to distribute your game.
> Platforms like Steam, Epic, Gog which have a client.
> Websites which offer a simple download: Your website, itch.io?, Humble Bundle (when DRM-free)
> Platforms can offer some support with some points on my list like patching but as we want to support Website downloads and WASM well we should think about those issues as well.
> 
> ### Container
> We should have some kind of asset container/asset bundle files
> Something like Valves VPK. Do we have people on board who are experienced using the formats used by other engines?
> What would be the use case for a single container?
> What would be the use case for multiple containers? One per state? Different asset resolutions?
> What file size should a container have?
> Topics are fragmentation, seeking, syscalls, etc.
> 
> ### Patching
> Patching of asset "containers/files" should be possible (but maybe optional)
> Nobody likes to download the complete game after an update to the assets.
> ishitatsuyuki said in discord that patching is done by steam for example. But we should also support the use case of providing the installer/updater/patcher by yourself. For example when you provide DRM free versions on your homepage.
> 
> Also for WASM, there should be a way to patch a cached file rather than download the full new version of that file depending on size. Not sure if this would be possible. If we download single asset files (see further down) rather than containers, download of the new file version should be fine I guess.
> If we store a container in the browser cache or wherever downloading the whole container because of an update would be a bummer.
> 

Each distribution platform will probably have their own way of doing delta patching, and they'll almost certainly be file-oriented. We should probably be flexible as to how assets are packed into file containers and perhaps support pluggable logic for it to let users adapt to all the strange distribution platforms of the world.

It's important to separate the concepts of metadata and asset content. Metadata can contain which assets exist and where they are located to enable separate storage of asset content.

For example, Steam's patching does binary diffing per MB-sized blocks within files, as opposed to diffing entire files at a time. This means a new version of a packfile which adds an asset at the beginning, offsetting everything else, would probably have most of the entire file changed according to Steam's patching system.

Would love to hear some more specific limitations of various platforms to inform our design, as well as proposals we can use as a starting point.

> ### Integrity Protection
> Some kind of integrity protection would be nice.
> This should prevent parties from changing game content e.g. prefabs.
> A basic version could use checksums, but this could get quite resource intensive. I don't want to calculate the checksum for my cinematic intro video.
> Maybe different methods for kinds of assets? Checksums for prefabs should be fine.
> As Anti Cheat measurements are basically different layers, this is one of the basic ones to prevent the easiest kind of cheating.
> Should be configurable to allow some kind of modding.
 
Integrity checks should be on by default to reduce global programmer suffering. Meow hash is Sufficiently Fast, faster than modern x86 per-core memory bandwidth.

> ### Compression
> Compression would just increase load times. Most games with huge assets file most likely will use asset files that are compressed already (DXTn)
> Users can use their OS compression if they want to save space.

Users should be able to select compression algorithm on a per-asset basis to suit their use-case. LZ4 is a great default IMO, and in my experience speeds up loading times rather than slowing them down due to less IO and super fast decompression. Textures may have their own custom compression, but generally assets benefit from compression.

> ### Prevent asset extraction
> Some devs seem to care about asset extraction.
> One way to prevent that would be to encrypt the asset container on disk. But then we need to decrypt our assets during load, possibly increasing load times.
> Just encrypting our container would maybe result in the need to decrypt the whole container before actual loading can begin. This has to be avoided.
> Loading of a single file from this container should be possible.
> 
> We cannot count on obfuscation of our distributed file format, because eventually this would be well documented somewhere in the amethyst/atelier book.
> 
> We could have an index file which is encrypted using a strong encryption method and the actual assets are garbled. Essentially making the index file kind of a key for the asset container.
> A solution for this should include performance consideration.
> 
> Sure, there are always ways to extract assets (dumping them from your GPU e.g.) but remember: _layered security_.

This sounds like DRM, and should probably not be a priority at this time. If some company wants to contribute a DRM solution, I guess we could maybe include it but it's not something I particularly care to implement, as it's a very difficult problem.

> ### Asset Streaming
> No not streaming to your GPU but rather allowing the WASM game to load the assets from your server on load. So you only have to load files that you are loading right now. Reducing first loading times.
> After the first load, the file should be cached.
> Do we want to assemble a container in the browser our just store the single asset files in the cache?

I would like to call this "asset downloading" rather than "asset streaming", to reduce confusion with actual streaming interfaces a la `std::io::Read`. This is about downloading individual assets or groups of assets from the internet, right. I think this is a concept that can be combined with any local storage solution.

I'm not very familiar with the storage options for WASM games but I also imagine that we'd need a way to fetch asset content from HTTP endpoints for all platforms. I guess most of the HTTP scaffolding is done by the browser though, which is a difference compared to native.

> ### Installer (Windows)
> Do we want our own installer for windows?
> Or should we use (and provide information on how to use) something like NSIS with amethyst?
> Ref.: Patching and Platformless distribution.

I would rather not focus our time on installers if at all possible. There are too many ways to distribute, let's just make our stuff not fight with those distribution methods as much as we can. :)

> ### Support for early play
> Blizzards Battle.net client allows you to play the game before you finish downloading all assets.
> This is something our container should support as well. Maybe splitting high detail assets into a single container and the medium and low into another. Then someone can play with medium settings after downloading the first container and the high resolution asset container would be downloaded in the background.
> 
> Amethyst should be able to be notified that the download is finished and use the high res assets when notified if the user selected the high res assets in settings previously.
> (This, most likely, is not an issue for 2D games)

I believe Blizzard's solution pre-allocates large packfiles and keeps track of where assets should be, whether they have been downloaded etc. This allows them to load individual assets from disk without downloading a whole file, and allows downloading in the background. It's essentially just a database optimized for assets.

**Comment by khskarl** [comment]
### Distribution 
As many things in game dev, I believe that flexibility should be a first class passenger, with that in mind, personally I like how UE4 puts it's priorities:
>It provides a framework for managing Assets that can **divide content into chunks that make sense in the context of your project**, without losing the advantages of Unreal Engine 4's loose package architecture. It also provides a **set of tools to help audit disk and memory usage**, giving you the information you need to **optimize the organization of your Assets for cooking and chunking when deploying your game.**
[_Source_](https://docs.unrealengine.com/en-US/Engine/Basics/AssetsAndPackages/AssetManagement/index.html)


Both UE4 and Unity have conceps of `AssetBundles`, while not exactly the same thing, they are quite overlapping. Unity's definition:
> An AssetBundle is an archive file containing platform specific Assets (Models, Textures, Prefabs, Audio clips, and even entire Scenes) that can be loaded at runtime. AssetBundles can express dependencies between each other; e.g. a material in AssetBundle A can reference a texture in AssetBundle B. For efficient delivery over networks, AssetBundles can be compressed with a choice of built-in algorithms depending on use case requirements (LZMA and LZ4).
[_Source_](https://docs.unity3d.com/Manual/AssetBundlesIntro.html)

In summation, `AssetBundles` are packs of assets and references to other assets. That's a rather flexible approach that works great for both traditional PC/Console games and mobile/wasm (mobile/wasm are different use cases, but similar needs). 

A flexible non-opinionated `AssetBundle` approach and a robust set of diagnostic tools can assist and direct a developer to make their own opinionated decision on how they will handle their files for their use case. And AssetBundles allow for easier patching in general and more efficient caching in wasm games.

I'm not sure how well this covers the case of huge and efficient pack files, but I see no reason for this to not be able to escalate for such instance, that will mostly depend on the allocation strategy and our specific implementation.

### Container 
Well, `AssetBundles` once again! I'm not sure what else I can say, AssetBundles are pretty much containers.

### Support for early play
`AssetBundles` can help with that as well, actually Unity does something that can be easily extended for early play when compiling for WebGL. It downloads a simple default scene and then downloads all the assets via AssetBundles: https://docs.unity3d.com/Manual/webgl-building.html

**Comment by kabergstrom** [comment]
Packfiles are now implemented
